# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-06 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='recommend_course',
            new_name='recommend_courses',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='num',
            field=models.IntegerField(verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='why',
            field=models.CharField(max_length=255, verbose_name='为什么要学？'),
        ),
    ]
